import GET_APP_LIST_PAGINATED from './gql/queries/app/GET_APP_LIST_PAGINATED.js';
import GET_APP_KEYWORDS from './gql/queries/app/GET_APP_KEYWORDS.js';
import GET_APP_TOTAL_NUMBER from './gql/queries/app/GET_APP_TOTAL_NUMBER';
import EXPORT_APP_LIST from './gql/queries/app/EXPORT_APP_LIST';
import GET_APP_DETAILS_INFOS from './gql/queries/app/GET_APP_DETAILS_INFOS';
import GET_APP_DETAILS_EVOLUTIONS from './gql/queries/app/GET_APP_DETAILS_EVOLUTIONS';
import GET_APP_DETAILS_DEPENDENCIES from './gql/queries/app/GET_APP_DETAILS_DEPENDENCIES';
import GET_APP_DETAILS_QUALITY from './gql/queries/app/GET_APP_DETAILS_QUALITY';
import GET_APP_DETAILS_AUDIT_REPORTS from './gql/queries/app/GET_APP_DETAILS_AUDIT_REPORTS';

import GET_FAQ from './gql/queries/GET_FAQ';
import GET_NOTIFICATIONS from './gql/queries/GET_NOTIFICATIONS';

export {
    GET_APP_KEYWORDS,
    GET_APP_DETAILS_INFOS,
    GET_APP_DETAILS_EVOLUTIONS,
    GET_APP_DETAILS_DEPENDENCIES,
    GET_APP_DETAILS_QUALITY,
    GET_APP_DETAILS_AUDIT_REPORTS,
    GET_APP_LIST_PAGINATED,
    GET_APP_TOTAL_NUMBER,
    EXPORT_APP_LIST,
    GET_FAQ,
    GET_NOTIFICATIONS,
};
