export const codeSmellTypes = {
    Dependency: 'Dependency',
    Lighthouse: 'Lighthouse',
    'Code-Coupling': 'Code-Coupling',
    'Code-Duplication': 'Code-Duplication',
    'Code-Complexity': 'Code-Complexity',
    'Code-Compliance': 'Code-Compliance',
    'Code-Security': 'Code-Security',
};

export const codeSmellCategories = {
    deprecated: 'deprecated',
    outdated: 'outdated',
    performance: 'performance',
    seo: 'seo',
    accessibility: 'accessibility',
    'first-contentful-paint': 'first-contentful-paint',
    'largest-contentful-paint': 'largest-contentful-paint',
    'cumulative-layout-shift': 'cumulative-layout-shift',
    'circular-dependencies': 'circular-dependencies',
    'instability-index': 'instability-index',
    'efferent-coupling': 'efferent-coupling',
    'afferent-coupling': 'afferent-coupling',
    'maintainability-index': 'maintainability-index',
    'maintainability-index-project-average': 'maintainability-index-project-average',
    'cyclomatic-complexity': 'cyclomatic-complexity',
    'halstead-program-length': 'halstead-program-length',
    'halstead-program-volume': 'halstead-program-volume',
    'halstead-program-difficulty': 'halstead-program-difficulty',
    'halstead-program-effort': 'halstead-program-effort',
    'halstead-program-estimated-bugs': 'halstead-program-estimated-bugs',
    'halstead-program-time-to-implement': 'halstead-program-time-to-implement',
    'physical-sloc': 'physical-sloc',
    'logical-sloc': 'logical-sloc',
};
