import { codeSmellCategories, codeSmellTypes } from './CodeSmellConfig.js';

export const evolutionHelpStatus = {
    critical: 'critical',
    important: 'important',
    recommended: 'recommended',
};

export const defaultEvolutionHelpStatus = [
    {
        category: `${codeSmellTypes.Dependency}-${codeSmellCategories.deprecated}`,
        status: evolutionHelpStatus.critical,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes.Dependency}-${codeSmellCategories.outdated}`,
        status: evolutionHelpStatus.recommended,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories.performance}`,
        status: evolutionHelpStatus.critical,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories.seo}`,
        status: evolutionHelpStatus.important,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories.accessibility}`,
        status: evolutionHelpStatus.critical,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories['first-contentful-paint']}`,
        status: evolutionHelpStatus.critical,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories['largest-contentful-paint']}`,
        status: evolutionHelpStatus.critical,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories['cumulative-layout-shift']}`,
        status: evolutionHelpStatus.critical,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Coupling']}-${codeSmellCategories['circular-dependencies']}`,
        status: evolutionHelpStatus.critical,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Coupling']}-${codeSmellCategories['instability-index']}`,
        status: evolutionHelpStatus.important,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Coupling']}-${codeSmellCategories['efferent-coupling']}`,
        status: evolutionHelpStatus.important,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Coupling']}-${codeSmellCategories['afferent-coupling']}`,
        status: evolutionHelpStatus.important,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Duplication']}`,
        status: evolutionHelpStatus.important,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Complexity']}-${codeSmellCategories['maintainability-index']}`,
        status: evolutionHelpStatus.important,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Complexity']}-${codeSmellCategories['cyclomatic-complexity']}`,
        status: evolutionHelpStatus.important,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Compliance']}`,
        status: evolutionHelpStatus.important,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Security']}`,
        status: evolutionHelpStatus.recommended,
        title: 'Default Title',
        description: 'Default Description',
        links: [],
    },
];
