"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultEvolutionHelpStatus = exports.evolutionHelpStatus = void 0;
const CodeSmellConfig_1 = require("./CodeSmellConfig");
exports.evolutionHelpStatus = {
    critical: 'critical',
    important: 'important',
    recommended: 'recommended',
};
exports.defaultEvolutionHelpStatus = [
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Lighthouse}-${CodeSmellConfig_1.codeSmellCategories.seo}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        title: '',
        category: `${CodeSmellConfig_1.codeSmellTypes.Lighthouse}-${CodeSmellConfig_1.codeSmellCategories.accessibility}`,
        description: '',
        status: exports.evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Lighthouse}-${CodeSmellConfig_1.codeSmellCategories.performance}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Lighthouse}-${CodeSmellConfig_1.codeSmellCategories['first-contentful-paint']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Lighthouse}-${CodeSmellConfig_1.codeSmellCategories['largest-contentful-paint']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Lighthouse}-${CodeSmellConfig_1.codeSmellCategories['cumulative-layout-shift']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Lighthouse}-${CodeSmellConfig_1.codeSmellCategories['total-blocking-time']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Lighthouse}-${CodeSmellConfig_1.codeSmellCategories['speed-index']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Coupling']}-${CodeSmellConfig_1.codeSmellCategories['circular-dependencies']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Coupling']}-${CodeSmellConfig_1.codeSmellCategories['instability-index']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Coupling']}-${CodeSmellConfig_1.codeSmellCategories['efferent-coupling']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Coupling']}-${CodeSmellConfig_1.codeSmellCategories['afferent-coupling']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Complexity']}-${CodeSmellConfig_1.codeSmellCategories['maintainability-index']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Complexity']}-${CodeSmellConfig_1.codeSmellCategories['maintainability-index-project-average']}`,
        title: 'Default Title',
        description: 'Default Description',
        explanation: '',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Complexity']}-${CodeSmellConfig_1.codeSmellCategories['cyclomatic-complexity']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Modularity']}-${CodeSmellConfig_1.codeSmellCategories['interaction-density']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Modularity']}-${CodeSmellConfig_1.codeSmellCategories['independent-files-ratio']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Modularity']}-${CodeSmellConfig_1.codeSmellCategories['file-degree-centrality']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Modularity']}-${CodeSmellConfig_1.codeSmellCategories['file-in-degree-centrality']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Modularity']}-${CodeSmellConfig_1.codeSmellCategories['file-out-degree-centrality']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    ...CodeSmellConfig_1.securityAntiPatterns.map(({ category }) => ({
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Security']}-${category}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    })),
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Duplication']}-${CodeSmellConfig_1.codeSmellCategories['code-duplication-percent']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.recommended,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Complexity']}-${CodeSmellConfig_1.codeSmellCategories['physical-sloc']}`,
        title: 'Default Title',
        description: 'Default Description',
        explanation: '',
        status: exports.evolutionHelpStatus.recommended,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes['Code-Complexity']}-${CodeSmellConfig_1.codeSmellCategories['logical-sloc']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.recommended,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Dependency}-${CodeSmellConfig_1.codeSmellCategories['deprecated']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${CodeSmellConfig_1.codeSmellTypes.Dependency}-${CodeSmellConfig_1.codeSmellCategories['outdated']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: exports.evolutionHelpStatus.recommended,
        links: [],
    },
];
