export const codeSmellTypes: { [key: string]: string } = {
    Dependency: 'Dependency',
    Lighthouse: 'Lighthouse',
    'Code-Coupling': 'Code-Coupling',
    'Code-Duplication': 'Code-Duplication',
    'Code-Complexity': 'Code-Complexity',
    'Code-Security': 'Code-Security',
    'Code-Modularity': 'Code-Modularity',
};

export const codeSmellCategories: { [key: string]: string } = {
    deprecated: 'deprecated',
    outdated: 'outdated',
    seo: 'seo',
    accessibility: 'accessibility',
    performance: 'performance',
    'first-contentful-paint': 'first-contentful-paint',
    'largest-contentful-paint': 'largest-contentful-paint',
    'cumulative-layout-shift': 'cumulative-layout-shift',
    'total-blocking-time': 'total-blocking-time',
    'speed-index': 'speed-index',
    'circular-dependencies': 'circular-dependencies',
    'instability-index': 'instability-index',
    'efferent-coupling': 'efferent-coupling',
    'afferent-coupling': 'afferent-coupling',
    'maintainability-index': 'maintainability-index',
    'maintainability-index-project-average': 'maintainability-index-project-average',
    'cyclomatic-complexity': 'cyclomatic-complexity',
    'halstead-program-length': 'halstead-program-length',
    'halstead-program-volume': 'halstead-program-volume',
    'halstead-program-difficulty': 'halstead-program-difficulty',
    'halstead-program-effort': 'halstead-program-effort',
    'halstead-program-estimated-bugs': 'halstead-program-estimated-bugs',
    'halstead-program-time-to-implement': 'halstead-program-time-to-implement',
    'physical-sloc': 'physical-sloc',
    'logical-sloc': 'logical-sloc',
    'code-duplication-percent': 'code-duplication-percent',
    'code-duplication-total-duplicated-lines': 'code-duplication-total-duplicated-lines',
    'code-duplication-file': 'code-duplication-file',
    'interaction-density': 'interaction-density',
    'interaction-groups': 'interaction-groups',
    'independent-files-ratio': 'independent-files-ratio',
    'file-degree-centrality': 'file-degree-centrality',
    'file-in-degree-centrality': 'file-in-degree-centrality',
    'file-out-degree-centrality': 'file-out-degree-centrality',
};
