export const devOpsType = {
    DORA: 'DORA',
};

export const devOpsCategories = {
    LEAD_TIME_FOR_CHANGES: 'LEAD_TIME_FOR_CHANGES',
    LEAD_REVIEW_TIME: 'LEAD_REVIEW_TIME',
    DEPLOYMENT_FREQUENCY: 'DEPLOYMENT_FREQUENCY',
    CHANGE_FAILURE_RATE: 'CHANGE_FAILURE_RATE',
    MEAN_TIME_TO_RESTORE_SERVICE: 'MEAN_TIME_TO_RESTORE_SERVICE',
    UP_TIME_AVERAGE: 'UP_TIME_AVERAGE',
};
