import { EvolutionHelpInputType } from '../types/EvolutionHelpType.ts';
import { codeSmellCategories, codeSmellTypes, securityAntiPatterns } from './CodeSmellConfig.ts';

export const evolutionHelpStatus: Record<string, string> = {
    critical: 'critical',
    important: 'important',
    recommended: 'recommended',
};

export const defaultEvolutionHelpStatus: EvolutionHelpInputType[] = [
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories.seo}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        title: '',
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories.accessibility}`,
        description: '',
        status: evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories.performance}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories['first-contentful-paint']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories['largest-contentful-paint']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories['cumulative-layout-shift']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories['total-blocking-time']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${codeSmellTypes.Lighthouse}-${codeSmellCategories['speed-index']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Coupling']}-${codeSmellCategories['circular-dependencies']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.critical,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Coupling']}-${codeSmellCategories['instability-index']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Coupling']}-${codeSmellCategories['efferent-coupling']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Coupling']}-${codeSmellCategories['afferent-coupling']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Complexity']}-${codeSmellCategories['maintainability-index']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Complexity']}-${codeSmellCategories['maintainability-index-project-average']}`,
        title: 'Default Title',
        description: 'Default Description',
        explanation: '',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Complexity']}-${codeSmellCategories['cyclomatic-complexity']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Modularity']}-${codeSmellCategories['interaction-density']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Modularity']}-${codeSmellCategories['independent-files-ratio']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Modularity']}-${codeSmellCategories['file-degree-centrality']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Modularity']}-${codeSmellCategories['file-in-degree-centrality']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Modularity']}-${codeSmellCategories['file-out-degree-centrality']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    ...securityAntiPatterns.map(({ category }) => ({
        category: `${codeSmellTypes['Code-Security']}-${category}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    })),
    {
        category: `${codeSmellTypes['Code-Duplication']}-${codeSmellCategories['code-duplication-percent']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.recommended,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Complexity']}-${codeSmellCategories['physical-sloc']}`,
        title: 'Default Title',
        description: 'Default Description',
        explanation: '',
        status: evolutionHelpStatus.recommended,
        links: [],
    },
    {
        category: `${codeSmellTypes['Code-Complexity']}-${codeSmellCategories['logical-sloc']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.recommended,
        links: [],
    },
    {
        category: `${codeSmellTypes.Dependency}-${codeSmellCategories['deprecated']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.important,
        links: [],
    },
    {
        category: `${codeSmellTypes.Dependency}-${codeSmellCategories['outdated']}`,
        title: 'Default Title',
        description: 'Default Description',
        status: evolutionHelpStatus.recommended,
        links: [],
    },
];
