name: Lint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm and install dependencies
        uses: ./.github/actions/setup-pnpm-node
        with:
          node-version: ${{ matrix.node-version }}

      - run: pnpm lint
